package io.github.nguyenyou.ui5.webcomponents.laminar.shared

type ButtonDesign                  = "Default" | "Positive" | "Negative" | "Transparent" | "Emphasized" | "Attention"
type ValueState                    = "None" | "Positive" | "Critical" | "Negative" | "Information"
type CompatTableGrowingMode        = "Button" | "Scroll" | "None"
type CompatTableMode               = "None" | "SingleSelect" | "MultiSelect"
type CompatTableColumnPopinDisplay = "Block" | "Inline"
type CompatTableRowType            = "Inactive" | "Active"
type SideContentFallDown           = "BelowXL" | "BelowL" | "BelowM" | "OnMinimumWidth"
type SideContentPosition           = "End" | "Start"
type SideContentVisibility         = "AlwaysShow" | "ShowAboveL" | "ShowAboveM" | "ShowAboveS" | "NeverShow"
type FCLLayout = "OneColumn" | "TwoColumnsStartExpanded" | "TwoColumnsMidExpanded" | "ThreeColumnsMidExpanded" |
  "ThreeColumnsEndExpanded" | "ThreeColumnsStartExpandedEndHidden" | "ThreeColumnsMidExpandedEndHidden" |
  "ThreeColumnsStartHiddenMidExpanded" | "ThreeColumnsStartHiddenEndExpanded" | "MidColumnFullScreen" |
  "EndColumnFullScreen"
type IllustrationMessageDesign = "Auto" | "Base" | "Dot" | "Spot" | "Dialog" | "Scene" | "ExtraSmall" | "Small" |
  "Medium" | "Large"
type MediaGalleryLayout              = "Auto" | "Vertical" | "Horizontal"
type MediaGalleryMenuHorizontalAlign = "Left" | "Right"
type MediaGalleryMenuVerticalAlign   = "Top" | "Bottom"
type MediaGalleryItemLayout          = "Square" | "Wide"
type NavigationLayoutMode            = "Auto" | "Collapsed" | "Expanded"
type NotificationListGrowingMode     = "Button" | "None"
type NotificationListItemImportance  = "Standard" | "Important"
type WrappingType                    = "None" | "Normal"
type PageBackgroundDesign            = "List" | "Solid" | "Transparent"
type SideNavigationItemDesign        = "Default" | "Action"
type TimelineGrowingMode             = "Button" | "Scroll" | "None"
type TimelineLayout                  = "Vertical" | "Horizontal"
type UploadCollectionSelectionMode   = "None" | "Single" | "SingleStart" | "SingleEnd" | "SingleAuto" | "Multiple"
type Highlight                       = "None" | "Positive" | "Critical" | "Negative" | "Information"
type ListItemType                    = "Inactive" | "Active" | "Detail" | "Navigation"
type UploadState                     = "Complete" | "Error" | "Ready" | "Uploading"
type WizardContentLayout             = "MultipleSteps" | "SingleStep"
type AvatarColorScheme = "Auto" | "Accent1" | "Accent2" | "Accent3" | "Accent4" | "Accent5" | "Accent6" | "Accent7" |
  "Accent8" | "Accent9" | "Accent10" | "Placeholder"
type AvatarShape       = "Circle" | "Square"
type AvatarSize        = "XS" | "S" | "M" | "L" | "XL"
type AvatarGroupType   = "Group" | "Individual"
type BarAccessibleRole = "Toolbar" | "None"
type BarDesign         = "Header" | "Subheader" | "Footer" | "FloatingFooter"
type BreadcrumbsDesign = "Standard" | "NoCurrentPage"
type BreadcrumbsSeparator = "Slash" | "BackSlash" | "DoubleBackSlash" | "DoubleGreaterThan" | "DoubleSlash" |
  "GreaterThan"
type BusyIndicatorSize          = "S" | "M" | "L"
type BusyIndicatorTextPlacement = "Top" | "Bottom"
type ButtonAccessibleRole       = "Button" | "Link"
type ButtonType                 = "Button" | "Submit" | "Reset"
type ButtonBadgeDesign          = "InlineText" | "OverlayText" | "AttentionDot"
type CalendarWeekNumbering      = "Default" | "ISO_8601" | "MiddleEastern" | "WesternTraditional"
type CalendarType               = "Gregorian" | "Islamic" | "Japanese" | "Buddhist" | "Persian"
type CalendarSelectionMode      = "Single" | "Multiple" | "Range"
type CalendarLegendItemType = "Today" | "Selected" | "None" | "Working" | "NonWorking" | "Type01" | "Type02" |
  "Type03" | "Type04" | "Type05" | "Type06" | "Type07" | "Type08" | "Type09" | "Type10" | "Type11" | "Type12" |
  "Type13" | "Type14" | "Type15" | "Type16" | "Type17" | "Type18" | "Type19" | "Type20"
type CarouselArrowsPlacement    = "Content" | "Navigation"
type BackgroundDesign           = "Solid" | "Transparent" | "Translucent"
type BorderDesign               = "Solid" | "None"
type CarouselPageIndicatorType  = "Default" | "Numeric"
type ComboBoxFilter             = "StartsWithPerTerm" | "StartsWith" | "Contains" | "None"
type PopupAccessibleRole        = "None" | "Dialog" | "AlertDialog"
type TextEmptyIndicatorMode     = "Off" | "On"
type ExpandableTextOverflowMode = "InPlace" | "Popover"
type TitleLevel                 = "H1" | "H2" | "H3" | "H4" | "H5" | "H6"
type FormItemSpacing            = "Normal" | "Large"
type IconDesign = "Contrast" | "Critical" | "Default" | "Information" | "Negative" | "Neutral" | "NonInteractive" |
  "Positive"
type IconMode               = "Image" | "Decorative" | "Interactive"
type InputType              = "Text" | "Email" | "Number" | "Password" | "Tel" | "URL" | "Search"
type LinkAccessibleRole     = "Link" | "Button"
type LinkDesign             = "Default" | "Subtle" | "Emphasized"
type InteractiveAreaSize    = "Normal" | "Large"
type ListAccessibleRole     = "List" | "Menu" | "Tree" | "ListBox"
type ListGrowingMode        = "Button" | "Scroll" | "None"
type ListSelectionMode      = "None" | "Single" | "SingleStart" | "SingleEnd" | "SingleAuto" | "Multiple" | "Delete"
type ListSeparator          = "All" | "Inner" | "None"
type PopoverHorizontalAlign = "Center" | "Start" | "End" | "Stretch"
type MessageStripDesign     = "Information" | "Positive" | "Negative" | "Critical" | "ColorSet1" | "ColorSet2"
type PanelAccessibleRole    = "Complementary" | "Form" | "Region"
type PopoverPlacement       = "Start" | "End" | "Top" | "Bottom"
type PopoverVerticalAlign   = "Center" | "Top" | "Bottom" | "Stretch"
type RatingIndicatorSize    = "S" | "M" | "L"
type SegmentedButtonSelectionMode = "Single" | "Multiple"
type SwitchDesign                 = "Textual" | "Graphical"
type SemanticColor                = "Default" | "Positive" | "Negative" | "Critical" | "Neutral"
type OverflowMode                 = "End" | "StartAndEnd"
type TabLayout                    = "Inline" | "Standard"
type TableOverflowMode            = "Scroll" | "Popin"
type TableCellHorizontalAlign     = "Left" | "Start" | "Right" | "End" | "Center"
type TableGrowingMode             = "Button" | "Scroll"
type SortOrder                    = "None" | "Ascending" | "Descending"
type TableSelectionMode           = "None" | "Single" | "Multiple"
type TableSelectionBehavior       = "RowSelector" | "RowOnly"
type TagDesign                    = "Set1" | "Set2" | "Neutral" | "Information" | "Positive" | "Negative" | "Critical"
type TagSize                      = "S" | "L"
type ToastPlacement = "TopStart" | "TopCenter" | "TopEnd" | "MiddleStart" | "MiddleCenter" | "MiddleEnd" |
  "BottomStart" | "BottomCenter" | "BottomEnd"
type ToolbarAlign                = "Start" | "End"
type ToolbarDesign               = "Solid" | "Transparent"
type ToolbarItemOverflowBehavior = "Default" | "NeverOverflow" | "AlwaysOverflow"
