package io.github.nguyenyou.ui5.webcomponents.ui5Webcomponents

import org.scalablytyped.runtime.Shortcut
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distGeneratedThemesDynamicDateRangePopoverDotcssMod extends Shortcut {
  
  @JSImport("@ui5/webcomponents/dist/generated/themes/DynamicDateRangePopover.css", JSImport.Default)
  @js.native
  val default: /* [ui5-responsive-popover]::part(content){padding:0}[ui5-responsive-popover]{width:320px;height:512px}[ui5-responsive-popover]::part(content){width:320px;height:512px}.ui5-dynamic-date-range-option-container{display:flex;flex-direction:column;align-content:center;justify-content:space-around;height:100%;width:100%}.ui5-ddr-current-value{display:flex;justify-content:flex-start;align-items:center;height:50px;font-size:.875rem;font-family:var(--sapFontFamily);font-weight:400;color:var(--sapContentLabelColor);background-color:#d3d3d3;padding-inline-start:10px;font-style:italic;text-overflow:ellipsis;overflow:hidden}[ui5-responsive-popover]::part(footer){display:flex;justify-content:end;padding-top:.125rem;padding-bottom:.125rem}.ui5-ddr-arrow-back-btn{display:flex;justify-content:center;align-items:center;width:var(--_ui5-v2-12-0_calendar_header_arrow_button_width);background-color:var(--sapButton_Lite_Background);color:var(--sapButton_Lite_TextColor);cursor:pointer;overflow:hidden;white-space:nowrap;padding:0;font-size:var(--sapFontSize);user-select:none}.ui5-ddr-arrow-back-btn{border:var(--_ui5-v2-12-0_calendar_header_arrow_button_border);border-radius:var(--_ui5-v2-12-0_calendar_header_arrow_button_border_radius);display:flex;background-color:var(--sapButton_Lite_Background);border-color:var(--sapButton_Lite_BorderColor)}.ui5-ddr-arrow-back-btn-arrow-icon{color:currentColor;pointer-events:none}[ui5-responsive-popover]::part(header){display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}.ui5-ddr-header{display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}
    */ String = js.native
  
  type _To = /* [ui5-responsive-popover]::part(content){padding:0}[ui5-responsive-popover]{width:320px;height:512px}[ui5-responsive-popover]::part(content){width:320px;height:512px}.ui5-dynamic-date-range-option-container{display:flex;flex-direction:column;align-content:center;justify-content:space-around;height:100%;width:100%}.ui5-ddr-current-value{display:flex;justify-content:flex-start;align-items:center;height:50px;font-size:.875rem;font-family:var(--sapFontFamily);font-weight:400;color:var(--sapContentLabelColor);background-color:#d3d3d3;padding-inline-start:10px;font-style:italic;text-overflow:ellipsis;overflow:hidden}[ui5-responsive-popover]::part(footer){display:flex;justify-content:end;padding-top:.125rem;padding-bottom:.125rem}.ui5-ddr-arrow-back-btn{display:flex;justify-content:center;align-items:center;width:var(--_ui5-v2-12-0_calendar_header_arrow_button_width);background-color:var(--sapButton_Lite_Background);color:var(--sapButton_Lite_TextColor);cursor:pointer;overflow:hidden;white-space:nowrap;padding:0;font-size:var(--sapFontSize);user-select:none}.ui5-ddr-arrow-back-btn{border:var(--_ui5-v2-12-0_calendar_header_arrow_button_border);border-radius:var(--_ui5-v2-12-0_calendar_header_arrow_button_border_radius);display:flex;background-color:var(--sapButton_Lite_Background);border-color:var(--sapButton_Lite_BorderColor)}.ui5-ddr-arrow-back-btn-arrow-icon{color:currentColor;pointer-events:none}[ui5-responsive-popover]::part(header){display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}.ui5-ddr-header{display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}
    */ String
  
  /* This means you don't have to write `default`, but can instead just say `distGeneratedThemesDynamicDateRangePopoverDotcssMod.foo` */
  override def _to: /* [ui5-responsive-popover]::part(content){padding:0}[ui5-responsive-popover]{width:320px;height:512px}[ui5-responsive-popover]::part(content){width:320px;height:512px}.ui5-dynamic-date-range-option-container{display:flex;flex-direction:column;align-content:center;justify-content:space-around;height:100%;width:100%}.ui5-ddr-current-value{display:flex;justify-content:flex-start;align-items:center;height:50px;font-size:.875rem;font-family:var(--sapFontFamily);font-weight:400;color:var(--sapContentLabelColor);background-color:#d3d3d3;padding-inline-start:10px;font-style:italic;text-overflow:ellipsis;overflow:hidden}[ui5-responsive-popover]::part(footer){display:flex;justify-content:end;padding-top:.125rem;padding-bottom:.125rem}.ui5-ddr-arrow-back-btn{display:flex;justify-content:center;align-items:center;width:var(--_ui5-v2-12-0_calendar_header_arrow_button_width);background-color:var(--sapButton_Lite_Background);color:var(--sapButton_Lite_TextColor);cursor:pointer;overflow:hidden;white-space:nowrap;padding:0;font-size:var(--sapFontSize);user-select:none}.ui5-ddr-arrow-back-btn{border:var(--_ui5-v2-12-0_calendar_header_arrow_button_border);border-radius:var(--_ui5-v2-12-0_calendar_header_arrow_button_border_radius);display:flex;background-color:var(--sapButton_Lite_Background);border-color:var(--sapButton_Lite_BorderColor)}.ui5-ddr-arrow-back-btn-arrow-icon{color:currentColor;pointer-events:none}[ui5-responsive-popover]::part(header){display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}.ui5-ddr-header{display:flex;flex-direction:row;align-items:center;justify-content:flex-start;height:2.5rem}
    */ String = default
}
