package io.github.nguyenyou.ui5.webcomponents.ui5WebcomponentsFiori

import org.scalablytyped.runtime.Shortcut
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distGeneratedThemesSearchItemDotcssMod extends Shortcut {
  
  @JSImport("@ui5/webcomponents-fiori/dist/generated/themes/SearchItem.css", JSImport.Default)
  @js.native
  val default: /* :host([selected]){border:none}:host{border:none}.ui5-search-item-content{width:100%;height:100%;display:flex;align-items:center;gap:1rem}.ui5-search-item-begin-content{display:flex;height:100%;align-items:center;gap:.75rem;width:100%;box-sizing:border-box;flex:1}.ui5-search-item-selected-delete{display:none}:host([selected]:hover),:host(:focus-within){.ui5-search-item-selected-delete{display:inline-block}}.ui5-search-item-text{display:inline-block;font-size:var(--sapFontLargeSize);font-family:var(--sapFontFamily);font-weight:400;color:var(--sapList_TextColor);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ui5-search-item-titles-container{overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;flex:1}.ui5-search-item-icon{padding:.375rem;width:1.25rem;height:1rem;box-sizing:content-box}:host([description]){height:auto;min-height:var(--_ui5-v2-11-0_list_item_base_height)}:host([description]) .ui5-search-item-content{padding-top:.5rem;padding-bottom:.5rem}:host([description]) .ui5-search-item-description{display:inline-block}.ui5-search-item-description{display:none;font-family:var(--sapFontFamily);font-size:var(--sapFontSize);font-weight:400;color:var(--sapContent_LabelColor);margin-top:.25rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    */ String = js.native
  
  type _To = /* :host([selected]){border:none}:host{border:none}.ui5-search-item-content{width:100%;height:100%;display:flex;align-items:center;gap:1rem}.ui5-search-item-begin-content{display:flex;height:100%;align-items:center;gap:.75rem;width:100%;box-sizing:border-box;flex:1}.ui5-search-item-selected-delete{display:none}:host([selected]:hover),:host(:focus-within){.ui5-search-item-selected-delete{display:inline-block}}.ui5-search-item-text{display:inline-block;font-size:var(--sapFontLargeSize);font-family:var(--sapFontFamily);font-weight:400;color:var(--sapList_TextColor);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ui5-search-item-titles-container{overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;flex:1}.ui5-search-item-icon{padding:.375rem;width:1.25rem;height:1rem;box-sizing:content-box}:host([description]){height:auto;min-height:var(--_ui5-v2-11-0_list_item_base_height)}:host([description]) .ui5-search-item-content{padding-top:.5rem;padding-bottom:.5rem}:host([description]) .ui5-search-item-description{display:inline-block}.ui5-search-item-description{display:none;font-family:var(--sapFontFamily);font-size:var(--sapFontSize);font-weight:400;color:var(--sapContent_LabelColor);margin-top:.25rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    */ String
  
  /* This means you don't have to write `default`, but can instead just say `distGeneratedThemesSearchItemDotcssMod.foo` */
  override def _to: /* :host([selected]){border:none}:host{border:none}.ui5-search-item-content{width:100%;height:100%;display:flex;align-items:center;gap:1rem}.ui5-search-item-begin-content{display:flex;height:100%;align-items:center;gap:.75rem;width:100%;box-sizing:border-box;flex:1}.ui5-search-item-selected-delete{display:none}:host([selected]:hover),:host(:focus-within){.ui5-search-item-selected-delete{display:inline-block}}.ui5-search-item-text{display:inline-block;font-size:var(--sapFontLargeSize);font-family:var(--sapFontFamily);font-weight:400;color:var(--sapList_TextColor);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ui5-search-item-titles-container{overflow:hidden;display:flex;flex-direction:column;justify-content:space-between;flex:1}.ui5-search-item-icon{padding:.375rem;width:1.25rem;height:1rem;box-sizing:content-box}:host([description]){height:auto;min-height:var(--_ui5-v2-11-0_list_item_base_height)}:host([description]) .ui5-search-item-content{padding-top:.5rem;padding-bottom:.5rem}:host([description]) .ui5-search-item-description{display:inline-block}.ui5-search-item-description{display:none;font-family:var(--sapFontFamily);font-size:var(--sapFontSize);font-weight:400;color:var(--sapContent_LabelColor);margin-top:.25rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
    */ String = default
}
