package io.github.nguyenyou.ui5.webcomponents.ui5WebcomponentsFiori

import org.scalablytyped.runtime.Shortcut
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distGeneratedThemesNavigationMenuItemDotcssMod extends Shortcut {
  
  @JSImport("@ui5/webcomponents-fiori/dist/generated/themes/NavigationMenuItem.css", JSImport.Default)
  @js.native
  val default: /* :host::part(native-li):after{border-radius:.375rem;inset:0}:host{display:flex;align-items:center;width:100%;box-sizing:border-box;position:relative;height:var(--_ui5-v2-11-0_side_navigation_item_height);min-height:var(--_ui5-v2-11-0_side_navigation_item_height);border-radius:.375rem;transition:var(--_ui5-v2-11-0_side_navigation_item_transition);color:var(--sapList_TextColor);font-size:var(--sapFontSize);font-family:var(--_ui5-v2-11-0_side_navigation_parent_item_font_family)}::slotted([ui5-navigation-menu-item]){font-family:"72override",var(--sapFontFamily)}:host([design="Action"]){color:var(--sapButton_TextColor)}:host([ui5-navigation-menu-item][selected]){border-bottom:none}:host([ui5-navigation-menu-item])::part(native-li){padding-left:var(--_ui5-v2-11-0_side_navigation_item_padding_start_in_overflow_popup);width:auto;border-radius:inherit}:host::part(content){color:inherit;font-family:inherit}:host .ui5-navmenu-item-link{text-decoration:none;color:inherit}.ui5-navigation-menu-item-root .ui5-menu-item-icon-end{position:relative;inset-inline-end:auto;width:.75rem;height:.75rem;color:inherit}.ui5-navigation-menu-item-root .ui5-sn-item-external-link-icon{height:.875rem}:host([design="Action"]) .ui5-sn-item-external-link-icon{color:var(--sapButton_TextColor)}:host([disabled]) .ui5-sn-item-external-link-icon{opacity:var(--sapContent_DisabledOpacity)}:host::part(icon){color:inherit;min-width:1rem;min-height:1rem}:host([disabled][active][actionable]) .ui5-li-root .ui5-li-icon{color:inherit}:host([focused]):not([active]){background:none}.ui5-menu-rp{padding:var(--_ui5-v2-11-0_side_navigation_popup_padding)}::slotted([ui5-navigation-menu-item]:not(:last-of-type)){margin-block-end:var(--_ui5-v2-11-0_side_navigation_item_bottom_margin)}
    */ String = js.native
  
  type _To = /* :host::part(native-li):after{border-radius:.375rem;inset:0}:host{display:flex;align-items:center;width:100%;box-sizing:border-box;position:relative;height:var(--_ui5-v2-11-0_side_navigation_item_height);min-height:var(--_ui5-v2-11-0_side_navigation_item_height);border-radius:.375rem;transition:var(--_ui5-v2-11-0_side_navigation_item_transition);color:var(--sapList_TextColor);font-size:var(--sapFontSize);font-family:var(--_ui5-v2-11-0_side_navigation_parent_item_font_family)}::slotted([ui5-navigation-menu-item]){font-family:"72override",var(--sapFontFamily)}:host([design="Action"]){color:var(--sapButton_TextColor)}:host([ui5-navigation-menu-item][selected]){border-bottom:none}:host([ui5-navigation-menu-item])::part(native-li){padding-left:var(--_ui5-v2-11-0_side_navigation_item_padding_start_in_overflow_popup);width:auto;border-radius:inherit}:host::part(content){color:inherit;font-family:inherit}:host .ui5-navmenu-item-link{text-decoration:none;color:inherit}.ui5-navigation-menu-item-root .ui5-menu-item-icon-end{position:relative;inset-inline-end:auto;width:.75rem;height:.75rem;color:inherit}.ui5-navigation-menu-item-root .ui5-sn-item-external-link-icon{height:.875rem}:host([design="Action"]) .ui5-sn-item-external-link-icon{color:var(--sapButton_TextColor)}:host([disabled]) .ui5-sn-item-external-link-icon{opacity:var(--sapContent_DisabledOpacity)}:host::part(icon){color:inherit;min-width:1rem;min-height:1rem}:host([disabled][active][actionable]) .ui5-li-root .ui5-li-icon{color:inherit}:host([focused]):not([active]){background:none}.ui5-menu-rp{padding:var(--_ui5-v2-11-0_side_navigation_popup_padding)}::slotted([ui5-navigation-menu-item]:not(:last-of-type)){margin-block-end:var(--_ui5-v2-11-0_side_navigation_item_bottom_margin)}
    */ String
  
  /* This means you don't have to write `default`, but can instead just say `distGeneratedThemesNavigationMenuItemDotcssMod.foo` */
  override def _to: /* :host::part(native-li):after{border-radius:.375rem;inset:0}:host{display:flex;align-items:center;width:100%;box-sizing:border-box;position:relative;height:var(--_ui5-v2-11-0_side_navigation_item_height);min-height:var(--_ui5-v2-11-0_side_navigation_item_height);border-radius:.375rem;transition:var(--_ui5-v2-11-0_side_navigation_item_transition);color:var(--sapList_TextColor);font-size:var(--sapFontSize);font-family:var(--_ui5-v2-11-0_side_navigation_parent_item_font_family)}::slotted([ui5-navigation-menu-item]){font-family:"72override",var(--sapFontFamily)}:host([design="Action"]){color:var(--sapButton_TextColor)}:host([ui5-navigation-menu-item][selected]){border-bottom:none}:host([ui5-navigation-menu-item])::part(native-li){padding-left:var(--_ui5-v2-11-0_side_navigation_item_padding_start_in_overflow_popup);width:auto;border-radius:inherit}:host::part(content){color:inherit;font-family:inherit}:host .ui5-navmenu-item-link{text-decoration:none;color:inherit}.ui5-navigation-menu-item-root .ui5-menu-item-icon-end{position:relative;inset-inline-end:auto;width:.75rem;height:.75rem;color:inherit}.ui5-navigation-menu-item-root .ui5-sn-item-external-link-icon{height:.875rem}:host([design="Action"]) .ui5-sn-item-external-link-icon{color:var(--sapButton_TextColor)}:host([disabled]) .ui5-sn-item-external-link-icon{opacity:var(--sapContent_DisabledOpacity)}:host::part(icon){color:inherit;min-width:1rem;min-height:1rem}:host([disabled][active][actionable]) .ui5-li-root .ui5-li-icon{color:inherit}:host([focused]):not([active]){background:none}.ui5-menu-rp{padding:var(--_ui5-v2-11-0_side_navigation_popup_padding)}::slotted([ui5-navigation-menu-item]:not(:last-of-type)){margin-block-end:var(--_ui5-v2-11-0_side_navigation_item_bottom_margin)}
    */ String = default
}
