package io.github.nguyenyou.ui5.webcomponents.ui5WebcomponentsFiori

import org.scalablytyped.runtime.Shortcut
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object distGeneratedThemesUploadCollectionDotcssMod extends Shortcut {
  
  @JSImport("@ui5/webcomponents-fiori/dist/generated/themes/UploadCollection.css.js", JSImport.Default)
  @js.native
  val default: /* :host(:not([hidden])){display:block}.ui5-uc-content{position:relative}.uc-no-files{background-color:var(--sapGroup_ContentBackground)}.uc-dnd-overlay{position:absolute;inset:.5rem;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius);container-type:size}.uc-drag-overlay{border:var(--ui5-v2-10-0_upload_collection_drag_overlay_border)}.uc-drop-overlay{border:var(--ui5-v2-10-0_upload_collection_drop_overlay_border)}.uc-dnd-overlay:before{content:"";position:absolute;inset:0;background-color:var(--sapGroup_ContentBackground);opacity:var(--ui5-v2-10-0_upload_collection_drag_overlay_opacity);border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-drop-overlay:after{content:"";position:absolute;inset:0;background-color:var(--ui5-v2-10-0_upload_collection_drop_overlay_background);opacity:.05;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-dnd-overlay [ui5-icon]{width:4rem;height:4rem;margin-bottom:1rem;color:var(--ui5-v2-10-0_upload_collection_drag_overlay_icon_color)}@container (max-height: 10rem){.uc-dnd-overlay [ui5-icon]{display:none}}.uc-dnd-overlay .dnd-overlay-text{font-family:"72override",var(--sapFontFamily);font-size:var(--sapFontHeader4Size);color:var(--ui5-v2-10-0_upload_collection_drag_overlay_text_color)}.uc-dnd-overlay [ui5-icon],.uc-dnd-overlay .dnd-overlay-text{z-index:1;pointer-events:none}.uc-drop-overlay [ui5-icon],.uc-drop-overlay .dnd-overlay-text{color:var(--sapContent_DragAndDropActiveColor)}.uc-no-files-dnd-overlay{visibility:hidden}
    */ String = js.native
  
  type _To = /* :host(:not([hidden])){display:block}.ui5-uc-content{position:relative}.uc-no-files{background-color:var(--sapGroup_ContentBackground)}.uc-dnd-overlay{position:absolute;inset:.5rem;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius);container-type:size}.uc-drag-overlay{border:var(--ui5-v2-10-0_upload_collection_drag_overlay_border)}.uc-drop-overlay{border:var(--ui5-v2-10-0_upload_collection_drop_overlay_border)}.uc-dnd-overlay:before{content:"";position:absolute;inset:0;background-color:var(--sapGroup_ContentBackground);opacity:var(--ui5-v2-10-0_upload_collection_drag_overlay_opacity);border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-drop-overlay:after{content:"";position:absolute;inset:0;background-color:var(--ui5-v2-10-0_upload_collection_drop_overlay_background);opacity:.05;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-dnd-overlay [ui5-icon]{width:4rem;height:4rem;margin-bottom:1rem;color:var(--ui5-v2-10-0_upload_collection_drag_overlay_icon_color)}@container (max-height: 10rem){.uc-dnd-overlay [ui5-icon]{display:none}}.uc-dnd-overlay .dnd-overlay-text{font-family:"72override",var(--sapFontFamily);font-size:var(--sapFontHeader4Size);color:var(--ui5-v2-10-0_upload_collection_drag_overlay_text_color)}.uc-dnd-overlay [ui5-icon],.uc-dnd-overlay .dnd-overlay-text{z-index:1;pointer-events:none}.uc-drop-overlay [ui5-icon],.uc-drop-overlay .dnd-overlay-text{color:var(--sapContent_DragAndDropActiveColor)}.uc-no-files-dnd-overlay{visibility:hidden}
    */ String
  
  /* This means you don't have to write `default`, but can instead just say `distGeneratedThemesUploadCollectionDotcssMod.foo` */
  override def _to: /* :host(:not([hidden])){display:block}.ui5-uc-content{position:relative}.uc-no-files{background-color:var(--sapGroup_ContentBackground)}.uc-dnd-overlay{position:absolute;inset:.5rem;display:flex;flex-direction:column;align-items:center;justify-content:center;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius);container-type:size}.uc-drag-overlay{border:var(--ui5-v2-10-0_upload_collection_drag_overlay_border)}.uc-drop-overlay{border:var(--ui5-v2-10-0_upload_collection_drop_overlay_border)}.uc-dnd-overlay:before{content:"";position:absolute;inset:0;background-color:var(--sapGroup_ContentBackground);opacity:var(--ui5-v2-10-0_upload_collection_drag_overlay_opacity);border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-drop-overlay:after{content:"";position:absolute;inset:0;background-color:var(--ui5-v2-10-0_upload_collection_drop_overlay_background);opacity:.05;border-radius:var(--ui5-v2-10-0_upload_collection_drag_overlay_border_radius)}.uc-dnd-overlay [ui5-icon]{width:4rem;height:4rem;margin-bottom:1rem;color:var(--ui5-v2-10-0_upload_collection_drag_overlay_icon_color)}@container (max-height: 10rem){.uc-dnd-overlay [ui5-icon]{display:none}}.uc-dnd-overlay .dnd-overlay-text{font-family:"72override",var(--sapFontFamily);font-size:var(--sapFontHeader4Size);color:var(--ui5-v2-10-0_upload_collection_drag_overlay_text_color)}.uc-dnd-overlay [ui5-icon],.uc-dnd-overlay .dnd-overlay-text{z-index:1;pointer-events:none}.uc-drop-overlay [ui5-icon],.uc-drop-overlay .dnd-overlay-text{color:var(--sapContent_DragAndDropActiveColor)}.uc-no-files-dnd-overlay{visibility:hidden}
    */ String = default
}
